/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-surface": "#2f3132",
        "hairline": "#e0e0e0",
        "on-secondary-fixed-variant": "#474649",
        "primary": "#004e9f",
        "outline-variant": "#c1c6d5",
        "on-tertiary-container": "#e0e8ff",
        "canvas-white": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline": "#727784",
        "critical-red": "#ff3b30",
        "error": "#ba1a1a",
        "surface-dim": "#d9dadc",
        "surface-container-low": "#f3f3f5",
        "on-primary-fixed-variant": "#00458e",
        "on-secondary-fixed": "#1b1b1d",
        "primary-fixed-dim": "#aac7ff",
        "primary-fixed": "#d7e3ff",
        "tertiary-fixed-dim": "#abc7ff",
        "surface-variant": "#e2e2e4",
        "inverse-primary": "#aac7ff",
        "surface-container": "#eeeef0",
        "ink": "#1d1d1f",
        "success-green": "#28a745",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#001b3f",
        "secondary-fixed": "#e4e2e4",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#00458f",
        "canvas-parchment": "#f5f5f7",
        "background": "#f9f9fb",
        "primary-container": "#0066cc",
        "tertiary-container": "#0066ce",
        "surface-container-high": "#e8e8ea",
        "error-container": "#ffdad6",
        "tertiary": "#004ea1",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#d7e2ff",
        "surface": "#f9f9fb",
        "surface-pearl": "#fafafc",
        "on-primary-container": "#dfe8ff",
        "secondary-fixed-dim": "#c8c6c8",
        "on-surface-variant": "#414753",
        "on-error": "#ffffff",
        "secondary-container": "#e2dfe1",
        "on-background": "#1a1c1d",
        "surface-container-highest": "#e2e2e4",
        "surface-tint": "#005cba",
        "on-error-container": "#93000a",
        "warning-amber": "#ff9f0a",
        "inverse-on-surface": "#f0f0f2",
        "on-surface": "#1a1c1d",
        "on-secondary-container": "#636264",
        "on-primary-fixed": "#001b3e",
        "secondary": "#5f5e60",
        "surface-bright": "#f9f9fb",
        "sky-link": "#2997ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-desktop": "40px",
        "xl": "32px",
        "section": "80px",
        "sm": "12px",
        "xxs": "4px",
        "margin-mobile": "16px",
        "base": "8px",
        "gutter": "24px",
        "lg": "24px",
        "xxl": "48px",
        "md": "17px",
        "xs": "8px"
      },
      "fontFamily": {
        "body": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "data-tabular": ["Inter"],
        "display-lg": ["Inter"],
        "lead": ["Inter"],
        "hero-display": ["Inter"],
        "tagline": ["Inter"],
        "display-md": ["Inter"],
        "label-capsule": ["Inter"],
        "nav-link": ["Inter"],
        "body-strong": ["Inter"]
      },
      "fontSize": {
        "body": ["17px", { "lineHeight": "1.47", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "data-tabular": ["13px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "display-lg": ["40px", { "lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "lead": ["28px", { "lineHeight": "1.14", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "hero-display": ["56px", { "lineHeight": "1.07", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "tagline": ["21px", { "lineHeight": "1.19", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "display-md": ["34px", { "lineHeight": "1.47", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-capsule": ["14px", { "lineHeight": "1.43", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "nav-link": ["12px", { "lineHeight": "1.0", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-strong": ["17px", { "lineHeight": "1.24", "letterSpacing": "-0.02em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
